Update to use React.forwardRef
buildo/react-autosize-textarea pull request #124
Opened 2019-02-14 07:11 UTC by alexlouden

I had a crack at this, unfortunately it's a breaking change for existing users of `innerRef`. I haven't used typescript much, just fudged my way through the types - hope it somewhat makes sense.

It's working for me with [`useRef`](https://reactjs.org/docs/hooks-reference.html#useref): https://codesandbox.io/s/3vj061pv9p

See #102

2019-02-26 17:47 UTC, giogonzo requested changes
Hi @alexlouden, thank you for this PR. It looks good to me (even though I'm not very familiar with the `createRef` API, it seems to use the strategy suggested in the docs here: https://reactjs.org/docs/forwarding-refs.html#forwarding-refs-in-higher-order-components).

> unfortunately it's a breaking change for existing users of `innerRef`

I'd say this is fine, we'll release as breaking.

One thing before we can merge: there are a lot unrelated of changes due to prettier formatting. Care to "Save without Formatting"?

2019-02-28 02:38 UTC, alexlouden commented
Thanks for the comment!

I've just discovered an issue with my implementation - if you don't pass in a ref the textarea doesn't autosize any more: https://codesandbox.io/s/73lrjyynp0

I'll fix this and the formatting changes - hopefully on the weekend.

2019-02-28 10:46 UTC, FrancescoCioria commented
> I've just discovered an issue with my implementation - if you don't pass in a ref the textarea doesn't autosize any more: https://codesandbox.io/s/73lrjyynp0

I've faced the same issue when I tried to implement it myself, I think I fixed it but I haven't tested enough to say if it's stable or not

You can see my try here: #125

2019-03-01 15:54 UTC, alexlouden commented
I'm wondering if we could check in the constructor if a ref was passed in, if not then we could create one instead with `createRef`?

2019-03-08 00:43 UTC, chrysb commented
The ref handling is preventing me from using this module... merge it baby! :)

2019-03-08 14:25 UTC, alexlouden commented
> The current ref handling is preventing me from using this module... merge it baby! :)

@chrysb in the meantime until we fix the issue I discovered above I've published my forked version and I've been using that - you're welcome to too: `@bonobolabs/react-autosize-textarea`

2019-03-26 09:49 UTC, FrancescoCioria commented
@alexlouden thank you for your work, It really helped me with the other PR ❤️

2019-03-26 09:49 UTC, closed without merging